name: Test
on: [pull_request]
jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Libraries
        run: |
          sudo apt-get update -y && sudo apt-get install -y python3-matplotlib
      - name: Run tests
        run: |
          cargo test -- --nocapture
